security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        in_memory:
            memory:
                users:
                    dummy_user:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        doc:
            pattern: ^/api/doc
            security: false 
        main:
            lazy: true
            provider: in_memory
            custom_authenticators:
                - App\Security\PresharedKeyAuthenticator 
            stateless: true
            entry_point: App\Security\AuthenticationEntryPoint    
    access_control:
            - { path: ^/, roles: IS_AUTHENTICATED_FULLY }  